# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wOhSgZCwW9GamTvfH4Ccj5sJ1ebwRyXZ
"""

!pip install fastapi uvicorn pydantic nest_asyncio
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

"""
DataShield Backend — Main Application Entry Point
Wires /api/scan to classification, sensitivity, rules, and scoring.
All business logic lives in dedicated modules.
"""

import uuid

from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError

from app.classifier import classify_field
from app.models import (
    LABEL_SOURCE_TO_CONFIDENCE,
    FieldResult,
    ScanRequest,
    ScanResponse,
)
from app.rules import is_reasonable
from app.scorer import score_scan
from app.sensitivity import get_sensitivity

app = FastAPI(
    title="DataShield API",
    description="Privacy risk scanning backend for the DataShield Chrome extension.",
    version="0.2.0",
)

from fastapi.middleware.cors import CORSMiddleware

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    first_error = exc.errors()[0]
    field_path = " -> ".join(str(loc) for loc in first_error.get("loc", []))
    message = first_error.get("msg", "Invalid request")
    return JSONResponse(
        status_code=422,
        content={"error": f"{field_path}: {message}" if field_path else message},
    )


@app.get("/")
async def root():
    return {"status": "ok", "service": "DataShield API"}


@app.post("/api/scan", response_model=ScanResponse)
async def scan(payload: ScanRequest):
    field_results = []
    sensitivities = []

    for field in payload.fields:
        category = classify_field(field)
        sensitivity = get_sensitivity(category)
        reasonable, note = is_reasonable(category, sensitivity, payload)

        field_results.append(
            FieldResult(
                field_id=field.field_id,
                sensitivity=sensitivity,
                reasonable=reasonable,
                label_confidence=LABEL_SOURCE_TO_CONFIDENCE[field.label_source],
                notes=note,
            )
        )
        sensitivities.append(sensitivity)

    overall_score, risk_level = score_scan(sensitivities)

    return ScanResponse(
        scan_id=str(uuid.uuid4())[:8],
        overall_score=overall_score,
        risk_level=risk_level,
        field_results=field_results,
    )

# Commented out IPython magic to ensure Python compatibility.
# Make sure you are inside the repo folder (replace 'repo-name' with your cloned folder's name if needed)
# %cd repo-name

# Install required backend packages
!pip install -r requirements.txt
# If there's no requirements.txt, run this instead:
# !pip install fastapi uvicorn pydantic nest_asyncio

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd Spider-Sense

# Install the necessary packages directly
!pip install fastapi uvicorn pydantic nest_asyncio

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

import subprocess
import time
import uvicorn
from threading import Thread

def run_app():
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=False)

Thread(target=run_app, daemon=True).start()
time.sleep(2)

print("Starting Tunnel... Look for the .trycloudflare.com URL below:\n")
!./cloudflared tunnel --url http://127.0.0.1:8000

# Commented out IPython magic to ensure Python compatibility.
# %cd <Spider-Sense>

# Commented out IPython magic to ensure Python compatibility.
# 1. Extract the uploaded ZIP file
!unzip -o Spider-Sense.zip

# 2. Navigate into the folder (no angle brackets)
# %cd Spider-Sense

# 3. Install requirements
!pip install fastapi uvicorn pydantic nest_asyncio

# 4. Download tunnel tool
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared

# 5. Launch FastAPI server and Cloudflare tunnel
import uvicorn
from threading import Thread
import time

def run_app():
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=False)

Thread(target=run_app, daemon=True).start()
time.sleep(2)

print("Starting Tunnel... Look for the .trycloudflare.com URL below:\n")
!./cloudflared tunnel --url http://127.0.0.1:8000

!curl -s http://127.0.0.1:8000/

import sys
import os

# 1. Ensure working directory and Python path are set to Spider-Sense
folder_path = "/content/Spider-Sense"
if os.path.exists(folder_path):
    os.chdir(folder_path)
    if folder_path not in sys.path:
        sys.path.insert(0, folder_path)
    print(f"Working directory set to: {os.getcwd()}")
else:
    print(f"Directory {folder_path} not found! Check if unzip succeeded.")

# 2. Test importing main to catch any missing libraries immediately
try:
    import main
    print("Successfully imported main.py!")
except Exception as e:
    print("CRITICAL IMPORT ERROR in main.py:")
    print(e)

# 3. Start Uvicorn in background
import uvicorn
import time
from threading import Thread

def run_app():
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=False)

Thread(target=run_app, daemon=True).start()
time.sleep(3)

# 4. Verify local port 8000 is responding
import urllib.request
try:
    response = urllib.request.urlopen("http://127.0.0.1:8000/")
    print("FastAPI is LIVE on 127.0.0.1:8000!")
except Exception as e:
    print(f"Local test connection result: {e}")

# 5. Launch Cloudflare Tunnel
print("\n--- Starting Cloudflare Tunnel ---")
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared
!./cloudflared tunnel --url http://127.0.0.1:8000

import os
import sys

# 1. Automatically locate the directory containing main.py
target_dir = None
for root, dirs, files in os.walk("/content"):
    if "main.py" in files:
        target_dir = root
        break

if target_dir:
    os.chdir(target_dir)
    if target_dir not in sys.path:
        sys.path.insert(0, target_dir)
    print(f"Found main.py in: {target_dir}")
else:
    print("CRITICAL: main.py was not found anywhere in /content!")

# 2. Test import
try:
    import main
    print("Successfully imported main.py!")
except Exception as e:
    print(f"Import Error: {e}")

# 3. Start Uvicorn
import uvicorn
import time
from threading import Thread

def run_app():
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=False)

Thread(target=run_app, daemon=True).start()
time.sleep(3)

# 4. Verify local port connection
import urllib.request
try:
    urllib.request.urlopen("http://127.0.0.1:8000/")
    print("FastAPI is LIVE on 127.0.0.1:8000!")
except Exception as e:
    print(f"Local connection test result: {e}")

# 5. Launch Cloudflare Tunnel
print("\n--- Starting Cloudflare Tunnel ---")
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared
!./cloudflared tunnel --url http://127.0.0.1:8000

import os
import sys

# Locate backend directory containing main.py
backend_dir = "/content/Spider-Sense/backend"
if not os.path.exists(backend_dir):
    for root, dirs, files in os.walk("/content"):
        if "main.py" in files:
            backend_dir = root
            break

os.chdir(backend_dir)

# Add backend directory to sys.path and system environment PYTHONPATH
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)
os.environ["PYTHONPATH"] = f"{backend_dir}:{os.environ.get('PYTHONPATH', '')}"

print(f"Active directory: {backend_dir}")

# Test import
try:
    import main
    print("Successfully imported main.py!")
except Exception as e:
    print(f"Import error: {e}")

# Launch FastAPI and Cloudflare
import uvicorn
import time
from threading import Thread

def run_app():
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=False)

Thread(target=run_app, daemon=True).start()
time.sleep(3)

print("\n--- Starting Cloudflare Tunnel ---")
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared
!./cloudflared tunnel --url http://127.0.0.1:8000

import os
import sys
import shutil

# 1. Locate 'Context Final.csv' across /content
target_csv = "Context Final.csv"
found_csv_path = None

for root, dirs, files in os.walk("/content"):
    if target_csv in files:
        found_csv_path = os.path.join(root, target_csv)
        print(f"Found dataset at: {found_csv_path}")
        break

# 2. Ensure /content/Spider-Sense/data/ exists and holds the CSV
expected_dir = "/content/Spider-Sense/data"
os.makedirs(expected_dir, exist_ok=True)
expected_csv_path = os.path.join(expected_dir, target_csv)

if found_csv_path and found_csv_path != expected_csv_path:
    shutil.copy(found_csv_path, expected_csv_path)
    print(f"Copied dataset to: {expected_csv_path}")
elif not found_csv_path and not os.path.exists(expected_csv_path):
    print(f"CRITICAL: '{target_csv}' was not found anywhere inside /content!")

# 3. Configure backend paths
backend_dir = "/content/Spider-Sense/backend"
if not os.path.exists(backend_dir):
    for root, dirs, files in os.walk("/content"):
        if "main.py" in files:
            backend_dir = root
            break

os.chdir(backend_dir)
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)
os.environ["PYTHONPATH"] = f"{backend_dir}:{os.environ.get('PYTHONPATH', '')}"

# 4. Test import
try:
    import main
    print("\nSUCCESS: main.py imported cleanly without errors!")
except Exception as e:
    print(f"\nImport Error: {e}")

# 5. Launch FastAPI and Cloudflare
import uvicorn
import time
from threading import Thread

def run_app():
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=False)

Thread(target=run_app, daemon=True).start()
time.sleep(3)

print("\n--- Starting Cloudflare Tunnel ---")
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared
!./cloudflared tunnel --url http://127.0.0.1:8000

import os
import sys
import shutil

# 1. Fix hyphen vs. space filename mismatch and sync across potential directories
source_csv = "/content/data/Context-Final.csv"

target_dirs = ["/content/data", "/content/Spider-Sense/data"]

for d in target_dirs:
    os.makedirs(d, exist_ok=True)
    if os.path.exists(source_csv):
        shutil.copy(source_csv, os.path.join(d, "Context Final.csv"))
        shutil.copy(source_csv, os.path.join(d, "Context-Final.csv"))

print("Dataset paths and filenames synchronized!")

# 2. Set backend directory paths
backend_dir = "/content/backend"
if not os.path.exists(backend_dir):
    backend_dir = "/content/Spider-Sense/backend"

os.chdir(backend_dir)

if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)
if "/content" not in sys.path:
    sys.path.insert(0, "/content")

os.environ["PYTHONPATH"] = f"{backend_dir}:/content:{os.environ.get('PYTHONPATH', '')}"

# 3. Test import
try:
    import main
    print("SUCCESS: main.py imported cleanly without errors!")
except Exception as e:
    print(f"Import Error: {e}")

# 4. Launch FastAPI and Cloudflare
import uvicorn
import time
from threading import Thread

def run_app():
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=False)

Thread(target=run_app, daemon=True).start()
time.sleep(3)

print("\n--- Starting Cloudflare Tunnel ---")
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared
!./cloudflared tunnel --url http://127.0.0.1:8000

import glob
import os
import shutil
import sys

# 1. Recursively find any CSV file under /content
found_csvs = glob.glob("/content/**/*.csv", recursive=True)
print(f"Found CSV files: {found_csvs}")

# 2. Replicate dataset to exact expected path
target_dir = "/content/Spider-Sense/data"
os.makedirs(target_dir, exist_ok=True)

if found_csvs:
    src_csv = found_csvs[0]
    shutil.copy(src_csv, os.path.join(target_dir, "Context Final.csv"))
    shutil.copy(src_csv, os.path.join(target_dir, "Context-Final.csv"))
    print(f"Successfully copied dataset to: {target_dir}/Context Final.csv")
else:
    print("ERROR: No CSV file was found inside /content!")

# 3. Configure backend paths
backend_dir = "/content/backend"
if not os.path.exists(backend_dir):
    for root, dirs, files in os.walk("/content"):
        if "main.py" in files:
            backend_dir = root
            break

os.chdir(backend_dir)
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)
if "/content" not in sys.path:
    sys.path.insert(0, "/content")

os.environ["PYTHONPATH"] = (
    f"{backend_dir}:/content:{os.environ.get('PYTHONPATH', '')}"
)

# 4. Test main import
try:
    import main

    print("\nSUCCESS: main.py imported cleanly without errors!")
except Exception as e:
    print(f"\nImport Error: {e}")

# 5. Launch FastAPI and Cloudflare
import time
from threading import Thread
import uvicorn


def run_app():
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=False)


Thread(target=run_app, daemon=True).start()
time.sleep(3)

print("\n--- Starting Cloudflare Tunnel ---")
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared
!./cloudflared tunnel --url http://127.0.0.1:8000

import glob
import os
import shutil
import sys

# 1. Target directory setup
target_dir = "/content/Spider-Sense/data"
os.makedirs(target_dir, exist_ok=True)

# 2. Find context dataset and ensure both space and hyphen named versions exist
found_csvs = glob.glob("/content/**/*.csv", recursive=True)
context_csvs = [f for f in found_csvs if "Context" in f]

if context_csvs:
    src_csv = context_csvs[0]
    dst_space = os.path.join(target_dir, "Context Final.csv")
    dst_hyphen = os.path.join(target_dir, "Context-Final.csv")

    for dst in [dst_space, dst_hyphen]:
        if os.path.abspath(src_csv) != os.path.abspath(dst):
            shutil.copy(src_csv, dst)

    print(f"Dataset active and verified at: {target_dir}")
else:
    print("ERROR: No Context CSV found inside /content!")

# 3. Configure backend paths
backend_dir = "/content/backend"
if not os.path.exists(backend_dir):
    for root, dirs, files in os.walk("/content"):
        if "main.py" in files:
            backend_dir = root
            break

os.chdir(backend_dir)
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)
if "/content" not in sys.path:
    sys.path.insert(0, "/content")

os.environ["PYTHONPATH"] = (
    f"{backend_dir}:/content:{os.environ.get('PYTHONPATH', '')}"
)

# 4. Test main import
try:
    import main

    print("\nSUCCESS: main.py imported cleanly without errors!")
except Exception as e:
    print(f"\nImport Error: {e}")

# 5. Launch FastAPI and Cloudflare
import time
from threading import Thread
import uvicorn


def run_app():
    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=False)


Thread(target=run_app, daemon=True).start()
time.sleep(3)

print("\n--- Starting Cloudflare Tunnel ---")
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
!chmod +x cloudflared
!./cloudflared tunnel --url http://127.0.0.1:8000

import glob
import os
import shutil
import sys
import time
from threading import Thread

# 1. Replicate dataset to all possible directory paths expected by rules.py
target_dirs = [
    "/content/data",
    "/content/Spider-Sense/data",
    "/content/backend/data",
]

found_csvs = glob.glob("/content/**/*.csv", recursive=True)
context_csvs = [
    f for f in found_csvs if "Context" in f and "sample_data" not in f
]

if context_csvs:
    src_csv = context_csvs[0]
    for d in target_dirs:
        os.makedirs(d, exist_ok=True)
        for name in ["Context Final.csv", "Context-Final.csv"]:
            dst = os.path.join(d, name)
            if os.path.abspath(src_csv) != os.path.abspath(dst):
                shutil.copy(src_csv, dst)
    print("Dataset successfully synchronized across all target directories.")
else:
    print("ERROR: Could not locate Context CSV file!")

# 2. Register all possible backend paths into sys.path to resolve 'app' imports
possible_paths = [
    "/content",
    "/content/backend",
    "/content/Spider-Sense",
    "/content/Spider-Sense/backend",
]

for p in possible_paths:
    if os.path.exists(p) and p not in sys.path:
        sys.path.insert(0, p)

os.environ["PYTHONPATH"] = (
    ":".join(possible_paths) + ":" + os.environ.get("PYTHONPATH", "")
)

# 3. Locate directory containing main.py and set working directory
for root, dirs, files in os.walk("/content"):
    if "main.py" in files and "sample_data" not in root:
        os.chdir(root)
        print(f"Set working directory to: {root}")
        break

# 4. Test import and determine Uvicorn entry point
app_module = None
try:
    import main

    app_module = "main:app"
    print("SUCCESS: Imported 'main' successfully!")
except Exception as e1:
    try:
        from app import main

        app_module = "app.main:app"
        print("SUCCESS: Imported 'app.main' successfully!")
    except Exception as e2:
        print(f"Direct Import Error: {e1}")
        print(f"Package Import Error: {e2}")

# 5. Launch FastAPI and Cloudflare Tunnel
if app_module:
    import uvicorn

    def run_app():
        uvicorn.run(app_module, host="127.0.0.1", port=8000, reload=False)

    Thread(target=run_app, daemon=True).start()
    time.sleep(3)

    print("\n--- Starting Cloudflare Tunnel ---")
    !wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
    !chmod +x cloudflared
    !./cloudflared tunnel --url http://127.0.0.1:8000

!fuser -k 8000/tcp

import os, sys, subprocess, time
from threading import Thread

# 1. Clean old repository and clone Himanshu's updated repo
!rm -rf Spider-Sense
!git clone https://github.com/Qypher365/Spider-Sense.git

# 2. Install updated dependencies
!pip install -q -r Spider-Sense/requirements.txt uvicorn nest_asyncio

# 3. Download cloudflared binary if missing
if not os.path.exists("cloudflared"):
    !wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared
    !chmod +x cloudflared

# 4. Add new repository path to sys.path
sys.path.insert(0, os.path.abspath("Spider-Sense"))

# 5. Launch Cloudflare Tunnel in background
def start_tunnel():
    subprocess.run(["./cloudflared", "tunnel", "--url", "http://127.0.0.1:8000"])

Thread(target=start_tunnel, daemon=True).start()

# 6. Run FastAPI server using new main:app
import nest_asyncio
import uvicorn

nest_asyncio.apply()

print("\n🚀 Starting server... Watch for your new trycloudflare.com URL in the logs below:\n")
time.sleep(3)

uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=False, app_dir="Spider-Sense")

import os, sys, subprocess, time, glob
from threading import Thread

# 1. Unzip uploaded code
!unzip -o /content/Spider-Sense.zip -d /content/

# 2. Locate main.py automatically
main_files = glob.glob('/content/**/main.py', recursive=True)
if main_files:
    target_dir = os.path.dirname(os.path.abspath(main_files[0]))
    print(f"✅ Found main.py in: {target_dir}")
    os.chdir(target_dir)
    sys.path.insert(0, target_dir)
else:
    raise FileNotFoundError("Could not locate main.py. Ensure your zip file contains main.py.")

# 3. Install core dependencies
req_files = glob.glob('/content/**/requirements.txt', recursive=True)
if req_files:
    !pip install -q -r {req_files[0]} uvicorn nest_asyncio
else:
    !pip install -q fastapi uvicorn pydantic scikit-learn pandas numpy nest_asyncio

# 4. Download and setup Cloudflare Tunnel
if not os.path.exists("/content/cloudflared"):
    !wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /content/cloudflared
    !chmod +x /content/cloudflared

def start_tunnel():
    subprocess.run(["/content/cloudflared", "tunnel", "--url", "http://127.0.0.1:8000"])

Thread(target=start_tunnel, daemon=True).start()

# 5. Start FastAPI
import nest_asyncio
import uvicorn
nest_asyncio.apply()

print("\n🚀 Starting server... Look for your trycloudflare.com URL below:\n")
time.sleep(3)
uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=False)

import os, sys, subprocess, time
from threading import Thread

# 1. Unzip uploaded code
!unzip -o /content/Spider-Sense.zip -d /content/

# 2. Set working path to backend folder so 'app' module resolves properly
backend_dir = "/content/Spider-Sense/backend"
if os.path.exists(backend_dir):
    os.chdir(backend_dir)
    sys.path.insert(0, backend_dir)
    print(f"✅ Set working directory to: {backend_dir}")

# 3. Install backend dependencies
req_file = f"{backend_dir}/requirements.txt"
if os.path.exists(req_file):
    !pip install -q -r {req_file} uvicorn nest_asyncio
else:
    !pip install -q fastapi uvicorn pydantic scikit-learn pandas numpy nest_asyncio

# 4. Ensure Cloudflare Tunnel is running
if not os.path.exists("/content/cloudflared"):
    !wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /content/cloudflared
    !chmod +x /content/cloudflared

def start_tunnel():
    subprocess.run(["/content/cloudflared", "tunnel", "--url", "http://127.0.0.1:8000"])

Thread(target=start_tunnel, daemon=True).start()

# 5. Start FastAPI entry point
import nest_asyncio
import uvicorn
nest_asyncio.apply()

print("\n🚀 Starting server... Look for your trycloudflare.com URL below:\n")
time.sleep(3)

uvicorn.run("app.main:app", host="127.0.0.1", port=8000, reload=False)

import os, sys, subprocess, time, glob, shutil
from threading import Thread

# 1. Unzip uploaded code
!unzip -o /content/Spider-Sense.zip -d /content/

# 2. Sync dataset file to all expected locations required by rules.py
csv_files = glob.glob('/content/**/Context*.csv', recursive=True)
if csv_files:
    dataset_source = csv_files[0]
    print(f"✅ Found dataset at: {dataset_source}")
    target_dirs = [
        "/content/Spider-Sense/data",
        "/content/data",
        "/content/Spider-Sense/backend/data"
    ]
    for target in target_dirs:
        os.makedirs(target, exist_ok=True)
        shutil.copy(dataset_source, os.path.join(target, "Context Final.csv"))
    print("✅ Synced 'Context Final.csv' to required directories.")
else:
    print("⚠️ Warning: Could not locate Context Final.csv in uploaded zip.")

# 3. Set working path to backend folder so 'app' module resolves
backend_dir = "/content/Spider-Sense/backend"
if os.path.exists(backend_dir):
    os.chdir(backend_dir)
    sys.path.insert(0, backend_dir)
    print(f"✅ Set working directory to: {backend_dir}")

# 4. Install backend dependencies
req_file = f"{backend_dir}/requirements.txt"
if os.path.exists(req_file):
    !pip install -q -r {req_file} uvicorn nest_asyncio
else:
    !pip install -q fastapi uvicorn pydantic scikit-learn pandas numpy nest_asyncio

# 5. Launch Cloudflare Tunnel
if not os.path.exists("/content/cloudflared"):
    !wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /content/cloudflared
    !chmod +x /content/cloudflared

def start_tunnel():
    subprocess.run(["/content/cloudflared", "tunnel", "--url", "http://127.0.0.1:8000"])

Thread(target=start_tunnel, daemon=True).start()

# 6. Start FastAPI entry point
import nest_asyncio
import uvicorn
nest_asyncio.apply()

print("\n🚀 Starting server... Watch for your trycloudflare.com URL below:\n")
time.sleep(3)

uvicorn.run("app.main:app", host="127.0.0.1", port=8000, reload=False)

import os, sys, subprocess, time, glob, shutil
from threading import Thread

# 1. Unzip uploaded code
!unzip -o /content/Spider-Sense.zip -d /content/

# 2. Sync dataset file to required directories
csv_files = glob.glob('/content/**/Context*.csv', recursive=True)
if csv_files:
    dataset_source = csv_files[0]
    print(f"✅ Found dataset at: {dataset_source}")
    target_dirs = [
        "/content/Spider-Sense/data",
        "/content/data",
        "/content/Spider-Sense/backend/data"
    ]
    for target in target_dirs:
        os.makedirs(target, exist_ok=True)
        shutil.copy(dataset_source, os.path.join(target, "Context Final.csv"))
    print("✅ Synced 'Context Final.csv' to required directories.")

# 3. Set working directory to backend folder
backend_dir = "/content/Spider-Sense/backend"
if os.path.exists(backend_dir):
    os.chdir(backend_dir)
    sys.path.insert(0, backend_dir)
    print(f"✅ Set working directory to: {backend_dir}")

# 4. Install backend dependencies
req_file = f"{backend_dir}/requirements.txt"
if os.path.exists(req_file):
    !pip install -q -r {req_file} uvicorn nest_asyncio
else:
    !pip install -q fastapi uvicorn pydantic scikit-learn pandas numpy nest_asyncio

# 5. Ensure Cloudflare Tunnel binary is ready
if not os.path.exists("/content/cloudflared"):
    !wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /content/cloudflared
    !chmod +x /content/cloudflared

# 6. Start FastAPI in a background thread to prevent loop conflict
def start_fastapi():
    import uvicorn
    uvicorn.run("app.main:app", host="127.0.0.1", port=8000, reload=False)

Thread(target=start_fastapi, daemon=True).start()
print("🚀 FastAPI server started on http://127.0.0.1:8000")
time.sleep(3)

# 7. Run Cloudflare Tunnel to display trycloudflare.com link live
!/content/cloudflared tunnel --url http://127.0.0.1:8000

!fuser -k 8000/tcp